manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: tklzg
      url-base: https://github.com/tklzg
    - name: stephen
      url-base: https://github.com/stephen
    - name: m165437
      url-base: https://github.com/M165437
  projects:
    - name: zmk
      import: app/west.yml
      remote: zmkfirmware
      revision: main
    - name: nice-view-gem
      remote: m165437
      revision: main
  self:
    path: config
